In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("recorded-offences.csv")

# View data
df.head()

        Code               Borough        Year    Value
0  E09000002  Barking and Dagenham  1999-12-31  19567.0
1  E09000002  Barking and Dagenham  2000-12-31  20253.0
2  E09000002  Barking and Dagenham  2001-12-31  20538.0
3  E09000002  Barking and Dagenham  2002-12-31  20394.0
4  E09000002  Barking and Dagenham  2003-12-31  22144.0

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(666, 4)
<class 'pandas.DataFrame'>
RangeIndex: 666 entries, 0 to 665
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Code     648 non-null    str
 1   Borough  666 non-null    str
 2   Year     666 non-null    str
 3   Value    659 non-null    float64
dtypes: float64(1), str(3)
memory usage: 39.8 KB
None
              Value
count  6.590000e+02
mean   1.538859e+05
std    6.483266e+05
min    2.484000e+03
25%    2.008600e+04
50%    2.747300e+04
75%    3.542300e+04
max    5.934580e+06

In [4]:
print(df.isnull().sum())

Code       18
Borough     0
Year        0
Value       7
dtype: int64

In [7]:
pd.get_dummies(df)

         Value  Code_727  ...  Year_2015-12-31  Year_2016-12-31
0      19567.0     False  ...            False            False
1      20253.0     False  ...            False            False
2      20538.0     False  ...            False            False
3      20394.0     False  ...            False            False
4      22144.0     False  ...            False            False
..         ...       ...  ...              ...              ...
661  3731338.0      True  ...            False            False
662        NaN      True  ...            False            False
663        NaN      True  ...            False            False
664        NaN      True  ...             True            False
665        NaN      True  ...            False             True

[666 rows x 92 columns]

In [9]:
[c for c in df.columns if "target" in c.lower()]

[]

In [12]:
print(df.columns)

Index(['Code', 'Borough', 'Year', 'Value'], dtype='str')

In [17]:
print(df.columns)

Index(['Code', 'Borough', 'Year', 'Value'], dtype='str')

In [23]:
df.head()
df.columns

Index(['Code', 'Borough', 'Year', 'Value'], dtype='str')

In [27]:
df.head()
df.columns

Index(['Code', 'Borough', 'Year', 'Value'], dtype='str')

In [34]:
df.head()
df.columns

Index(['Code', 'Borough', 'Year', 'Value'], dtype='str')