In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("public-challenges.csv")

df.head()

      Track                       Car  ...        Username  Finish Time
0  The Kyle  Caterham R500 Superlight  ...      LADY_FITCH    02:08.932
1  The Kyle  Caterham R500 Superlight  ...        iMmooddy    02:08.770
2  The Kyle  Caterham R500 Superlight  ...        ajfuzy24    02:09.000
3  The Kyle  Caterham R500 Superlight  ...     stefparrain    02:09.141
4  The Kyle  Caterham R500 Superlight  ...  Oliver18091970    02:09.270

[5 rows x 8 columns]

In [3]:
# Check missing values
print(df.isnull().sum())

# Fill missing values (simple strategy)
df = df.fillna(df.median(numeric_only=True))
df = df.fillna("missing")

Track            0
Car              0
Time of Day      0
Time Lapse       0
Cloud Cover      0
Precipitation    0
Username         0
Finish Time      0
dtype: int64

In [5]:
for col in df.select_dtypes(include=['string', 'object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [6]:
df = df.convert_dtypes()

In [8]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Track          11 non-null     Int64
 1   Car            11 non-null     Int64
 2   Time of Day    11 non-null     Int64
 3   Time Lapse     11 non-null     Int64
 4   Cloud Cover    11 non-null     Int64
 5   Precipitation  11 non-null     Int64
 6   Username       11 non-null     Int64
 7   Finish Time    11 non-null     Int64
dtypes: Int64(8)
memory usage: 924.0 bytes

In [11]:
df.head()

   Track  Car  Time of Day  ...  Precipitation  Username  Finish Time
0      0    0            0  ...              0         2            1
1      0    0            0  ...              0         7            0
2      0    0            0  ...              0         5            2
3      0    0            0  ...              0        10            3
4      0    0            0  ...              0         3            4

[5 rows x 8 columns]

In [15]:
print("X_train" in globals())

False

In [20]:
df.head()
df.columns

Index(['Track', 'Car', 'Time of Day', 'Time Lapse', 'Cloud Cover',
       'Precipitation', 'Username', 'Finish Time'],
      dtype='str')

In [26]:
df.columns

Index(['Track', 'Car', 'Time of Day', 'Time Lapse', 'Cloud Cover',
       'Precipitation', 'Username', 'Finish Time'],
      dtype='str')